version: '3.9'
services:
  homo-notifier:
    build: .
    env_file: .env
    volumes:
      - ./log/homo:/app/log
    restart: always

  genshin-notifier:
    build: .
    command: ["sh", "-c", "echo '0 18 * * * python /app/genshin-notifier/main.py >> /app/log/genshin_cron.log 2>&1' > /etc/cron.d/genshin_cron && crontab /etc/cron.d/genshin_cron && cron -f"]
    env_file: .env
    volumes:
      - ./log/genshin:/app/log
    restart: always